### ISSUE TITLE
ailed to solve puzzle: Task you are requesting does not exist in your current 

### ISSUE THREAD

**Issue by datasonglook** [Jaammerr/The-Dawn-Bot#1]
06:18:34 |  ERROR    | - Account: xxxxxx | Failed to solve puzzle: Task you are requesting does not exist in your current task list or has been expired. Expected integer number, but sent value 'None' | Retrying...
06:18:41 |  INFO     | - Account: xxxxxx | Got puzzle image, solving...
06:18:42 |  ERROR    | - Account: xxxxxx | Failed to solve puzzle: Task you are requesting does not exist in your current task list or has been expired. Expected integer number, but sent value 'None' | Retrying...

**Comment by Jaammerr** [comment]
I updated the code so you can see the complete error. Most likely you have a negative balance on the anti-captcha service.

**Comment by datasonglook** [comment]
ok

**Comment by datasonglook** [comment]
But I found that the decoding was unsuccessful, is it normal

00:14:51 |  ERROR    | - Account: xxx | Failed to farm: API returned an error: {'success': False, 'message': 'Incorrect answer. Try again!', 'msgcode': 1}

**Comment by Jaammerr** [comment]
Yes, it's normal, the service doesn't always send the right solution

And update to the latest version, I took this error into account
