### ISSUE TITLE
massive errors string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by zdrpepe** [Jaammerr/The-Dawn-Bot#10]
bot stopped working on all operating systems(ubuntu/windows)
errors of the following kind:
core.bot:get_captcha_data:40 - Account: xxx@fmaillerbox.com | Error occurred: string indices must be integers, not 'str' | Retrying...
core.bot:perform_farming_actions:245 - Account: xxx@mail.ru | Failed to get user info: string indices must be integers, not 'str'

**Comment by Jaammerr** [comment]
use version 1.4
