### ISSUE TITLE
whats problem?

### ISSUE THREAD

**Issue by sitxxar** [Jaammerr/The-Dawn-Bot#14]
![image](https://github.com/user-attachments/assets/a0c24ab2-8b8b-41cc-9bbb-6346cc2087a4)

**Comment by MrTimonM** [comment]
is this fixed now?

**Comment by sitxxar** [comment]
> is this fixed now?
still error

**Comment by MrTimonM** [comment]
> > is this fixed now?
> 
> still error, how about you?

I am not running yet

**Comment by Jaammerr** [comment]
You need to change the proxy or wait for some time, the rate limit is renewed automatically

If this happens during farming (if the initial login is successful), then the account will automatically go to sleep for some time.
