### ISSUE TITLE
Registration api error 

### ISSUE THREAD

**Issue by Dmkls** [Jaammerr/The-Dawn-Bot#15]
For some reason about 95% of attempts to register accounts end with the error “**05:02:10 | ERROR | - Account: *** | Failed to register: API returned an error: {'success': False, 'data': None, 'message': 'Something went wrong #BR4'}**” it appears right after solving the captcha. I've tried waiting and also registered several accounts manually, it turns out that the registration works stably
![pic](https://github.com/user-attachments/assets/8f143da5-ed52-4774-9e87-baf8366ee2d9)

authorization and other functions work well, thanks for the soft

**Comment by Jaammerr** [comment]
either bad proxies or a problem on the DAWN side with servers

try using other proxies
