### ISSUE TITLE
How many proxies can be configured at one time？

### ISSUE THREAD

**Issue by tahitimoon** [Jaammerr/The-Dawn-Bot#17]
How many proxies can be configured at one time？

**Comment by Jaammerr** [comment]
Before starting work, the script distributes 1 proxy to each account. If there are fewer proxies than accounts, the list will start over until all accounts have a proxy.

**Comment by bscongluanbui** [comment]
> Before starting work, the script distributes 1 proxy to each account. If there are fewer proxies than accounts, the list will start over until all accounts have a proxy.

How to use multiproxies with 1 accounts
