### ISSUE TITLE
CONNECT tunnel failed, response 502

### ISSUE THREAD

**Issue by datafu** [Jaammerr/The-Dawn-Bot#2]
10:18:39 |  ERROR    | - Account: xxxxx | Failed to register: Failed to perform, curl: (56) CONNECT tunnel failed, response 502. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
10:18:39 |  DEBUG    | - Results exported to results folder

I can successfully authenticate by copying the link directly to the webpage

**Comment by Jaammerr** [comment]
Most likely the problem is with your proxy, try using another one,
