### ISSUE TITLE
account IP allocation issue 

### ISSUE THREAD

**Issue by tahitimoon** [Jaammerr/The-Dawn-Bot#24]
If there are 3 accounts and 10 IPs, how will they be allocated? Is it still one account assigned to one IP, and the other IPs are not used? If it's one account with 10, will it still be one account assigned to one IP?

**Comment by Jaammerr** [comment]
Accounts are distributed in the order of the list 1 to 1. If you want to use several proxies for one account - just duplicate the lines.

**Comment by tahitimoon** [comment]
ths
