### ISSUE TITLE
register function need update

### ISSUE THREAD

**Issue by icelts** [Jaammerr/The-Dawn-Bot#27]
12:45:29 |  SUCCESS  | - Account: gdnoawssscvar@rambler.ru | Puzzle solved: CD&DRG 
12:45:30 |  ERROR    | - Account: gdnoawssscvar@rambler.ru | Failed to register: API returned an error: {'success': False, 'data': None, 'message': 'Something went wrong #BR4'}

**Comment by kucher93** [comment]
Rambler bannned

> 12:45:29 | SUCCESS | - Account: [gdnoawssscvar@rambler.ru](mailto:gdnoawssscvar@rambler.ru) | Puzzle solved: CD&DRG 12:45:30 | ERROR | - Account: [gdnoawssscvar@rambler.ru](mailto:gdnoawssscvar@rambler.ru) | Failed to register: API returned an error: {'success': False, 'data': None, 'message': 'Something went wrong #BR4'}

**Comment by Jaammerr** [comment]
use the latest version, they banned a lot of email domains
