### ISSUE TITLE
ISSUE #1

### ISSUE THREAD

**Issue by cryptoknightsz** [Jaammerr/The-Dawn-Bot#28]
![image](https://github.com/user-attachments/assets/58dc27f9-5017-4728-bdd9-cc3faf74f6a8)

**Comment by tahitimoon** [comment]
me too

**Comment by icelts** [comment]
same here

**Comment by Gritrunnn** [comment]
same here,why? anyone help

**Comment by XNFTHUNETRZ** [comment]
Did someone reported the same in his tg channel?

**Comment by Jaammerr** [comment]
They updated the extension today

I'll probably check it out tomorrow and make a new update

**Comment by XNFTHUNETRZ** [comment]
😽🫡

**Comment by Jaammerr** [comment]
updated 1.6, already works
