### ISSUE TITLE
Give you a piece of code that can help you！！The current version must provide a value for the APPID，Here's how to get it！Thank you for open source！！！！

### ISSUE THREAD

**Issue by EliseCaro** [Jaammerr/The-Dawn-Bot#29]
File path ：`chrome-extension://fpdkjdnhkakefebpekbdhillbhonfjjp/splash.js` （Open it after installing the extension）

![1733267051099](https://github.com/user-attachments/assets/9334eee9-ba2f-426b-afea-4e3fac6abed2)

((![1733266509540](https://github.com/user-attachments/assets/c94ccbe3-2c4c-43f4-ad5c-fe1a69bdeda5)))

**Comment by Jaammerr** [comment]
updated 1.6, already works
