### ISSUE TITLE
curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21048 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 03:31:57 |  ERROR    | - Account: dqwqlgfgrk@rambler.ru | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21048 ms: Couldn't connect to server. See 

### ISSUE THREAD

**Issue by datafu** [Jaammerr/The-Dawn-Bot#3]
03:30:52 |  ERROR    | - Account: ofnqhcbndt@rambler.ru | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21049 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
03:30:52 |  ERROR    | - Account: jmzkphaxvb@rambler.ru | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21051 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
03:30:52 |  ERROR    | - Account: vmfcxznhyt@rambler.ru | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21052 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
03:30:52 |  ERROR    | - Account: przcbetvrz@rambler.ru | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21051 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
03:30:52 |  ERROR    | - Account: rzgfswvequ@rambler.ru | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21052 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
03:30:52 |  INFO     | - Account: qkavlvujrn@rambler.ru | Logging in...
03:30:52 |  INFO     | - Account: logrofavbt@rambler.ru | Logging in...
03:30:52 |  INFO     | - Account: mkgzkfohnh@rambler.ru | Logging in...
03:30:52 |  INFO     | - Account: dqwqlgfgrk@rambler.ru | Logging in...
03:30:52 |  INFO     | - Account: areilmnabm@rambler.ru | Logging in...
03:31:57 |  ERROR    | - Account: logrofavbt@rambler.ru | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21031 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

These errors may occur after running the service for a period of time, but restarting it will restore normal operation

**Comment by Jaammerr** [comment]
The problem is in your operating system, rent a Linux server and install the software there via Docker (docker-farm branch in repo)

**Comment by datafu** [comment]
docker-compose up -d --build
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 23, in <module>
    from ..bundle import get_image_digests
  File "/usr/lib/python3/dist-packages/compose/bundle.py", line 12, in <module>
    from .config.serialize import denormalize_config
  File "/usr/lib/python3/dist-packages/compose/config/__init__.py", line 6, in <module>
    from .config import ConfigurationError
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 50, in <module>
    from .validation import match_named_volumes
  File "/usr/lib/python3/dist-packages/compose/config/validation.py", line 12, in <module>
    from jsonschema import Draft4Validator
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jsonschema/exceptions.py", line 14, in <module>
    from attrs import define
ModuleNotFoundError: No module named 'attrs'

**Comment by datafu** [comment]
> 03:30:52 | ERROR | - Account: [ofnqhcbndt@rambler.ru](mailto:ofnqhcbndt@rambler.ru) | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21049 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 03:30:52 | ERROR | - Account: [jmzkphaxvb@rambler.ru](mailto:jmzkphaxvb@rambler.ru) | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21051 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 03:30:52 | ERROR | - Account: [vmfcxznhyt@rambler.ru](mailto:vmfcxznhyt@rambler.ru) | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21052 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 03:30:52 | ERROR | - Account: [przcbetvrz@rambler.ru](mailto:przcbetvrz@rambler.ru) | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21051 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 03:30:52 | ERROR | - Account: [rzgfswvequ@rambler.ru](mailto:rzgfswvequ@rambler.ru) | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21052 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 03:30:52 | INFO | - Account: [qkavlvujrn@rambler.ru](mailto:qkavlvujrn@rambler.ru) | Logging in... 03:30:52 | INFO | - Account: [logrofavbt@rambler.ru](mailto:logrofavbt@rambler.ru) | Logging in... 03:30:52 | INFO | - Account: [mkgzkfohnh@rambler.ru](mailto:mkgzkfohnh@rambler.ru) | Logging in... 03:30:52 | INFO | - Account: [dqwqlgfgrk@rambler.ru](mailto:dqwqlgfgrk@rambler.ru) | Logging in... 03:30:52 | INFO | - Account: [areilmnabm@rambler.ru](mailto:areilmnabm@rambler.ru) | Logging in... 03:31:57 | ERROR | - Account: [logrofavbt@rambler.ru](mailto:logrofavbt@rambler.ru) | Failed to farm: Failed to send request after 3 attempts: Failed to perform, curl: (28) Failed to connect to gw-us.nstproxy.io port 24125 after 21031 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
> 
> These errors may occur after running the service for a period of time, but restarting it will restore normal operation
