### ISSUE TITLE
Failed to login: Session is rate limited

### ISSUE THREAD

**Issue by maianhbao1** [Jaammerr/The-Dawn-Bot#30]
how to fix

**Comment by renmengkai** [comment]
应该缺少appid，这个项目中没有获取appid，appid一直传的undefined

**Comment by tructhienbui** [comment]
Even with appid, still having same issue

**Comment by tructhienbui** [comment]
Dev is stupud, they even put wrong typo for "Bearer" token LOL. In their code: Berear

**Comment by JantGa** [comment]
> Dev is stupud, they even put wrong typo for "Bearer" token LOL. In their code: Berear
Bro，are you fix it?

**Comment by tructhienbui** [comment]
> > Dev is stupud, they even put wrong typo for "Bearer" token LOL. In their code: Berear
> > Bro，are you fix it?

I think currently only having issues with "register", the "farming" work very well

**Comment by JantGa** [comment]
> > > Dev is stupud, they even put wrong typo for "Bearer" token LOL. In their code: Berear
> > > Bro，are you fix it?
> 
> I think currently only having issues with "register", the "farming" work very well

got it,I'm try

**Comment by JantGa** [comment]
> > > Dev is stupud, they even put wrong typo for "Bearer" token LOL. In their code: Berear
> > > Bro，are you fix it?
> 
> I think currently only having issues with "register", the "farming" work very well. Also can say the register issues is from their API's end, not from code.

Does that mean you haven't encountered the same problem?

**Comment by mr-dvgiang** [comment]
> Dev is stupud, they even put wrong typo for "Bearer" token LOL. In their code: BerearDev thật ngu ngốc, họ thậm chí còn đặt sai chính tả cho mã thông báo "Người mang" LOL. Trong mã của họ: Berear

Người ta share free, ông dùng thấy sai thì nên góp ý. DM giỏi thì tự làm đi. NC trẻ trâu vcl

**Comment by xinzhongyouhai** [comment]
膜拜@Jaammerr
