### ISSUE TITLE
the memory keeps increasing

### ISSUE THREAD

**Issue by flyrainsong** [Jaammerr/The-Dawn-Bot#4]
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                            1199150 root      20   0 1460716 520768  18644 S   6.0  25.8   6:37.67 python ./run.py

When running the Docker version, I found that the memory keeps increasing. Why is this

**Comment by Jaammerr** [comment]
hi, thanks for the feedback, I didn't see such a problem, but after checking it turned out to be true

I'll try to find and fix it soon

**Comment by Jaammerr** [comment]
Unfortunately, I couldn't find the exact reason, but I see that a large amount of memory is going to the clipboard, most likely this is a forced python process.

In the latest version, I do not see any problems with the work (the script has been actively working in docker for more than 72 hours), so just don't pay attention to it -_-
