### ISSUE TITLE
[add feature] bind proxy ip to account

### ISSUE THREAD

**Issue by y3zha** [Jaammerr/The-Dawn-Bot#8]
add a account_proxy.txt in config/data

email:password:proxy

if i use farm module, it will read the data

**Comment by y3zha** [comment]
It seems that if I have several proxies, one account can not bonus from these proxies?only can bonus from one proxy?

**Comment by Jaammerr** [comment]
there is no point, at first the script already distributes proxies for each account, and this order never changes (if the order of accounts and proxies remains the same)

no, there are no networks like in grass, here just keepalive requests are sent
